set -g @plugin 'tmux-plugins/tpm' 
set -g @plugin 'tmux-plugins/tmux-sensible'

# PI setup
set -g extended-keys on
set -g extended-keys-format csi-u


# yazi image preview settings
set -g allow-passthrough on
set -g visual-activity off
set-option -g focus-events on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set-option -g status-position top
setw -g mode-keys vi

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'
set -g @plugin 'alexwforsythe/tmux-which-key'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
set -g default-command "fish"
