// Content Quality Scoring — Multi-language, section-aware version
// Usage: node score.js <locale>
// Env vars:
//   OUTPUT_DIR        — output directory (required, e.g., content-quality/ACTB-2314-xxx)
//   RUN_TAG           — optional tag for input/output filenames (e.g., "indonesia")
//   OPENAI_BASE_URL   — LLM endpoint (default: https://genai-gateway.agoda.is/v1)
//   SCORE_MODEL       — LLM model name (default: gemini-3.1-pro)
//   SCORE_CONCURRENCY — parallel scoring workers (default: 5)

const OpenAI = require('openai');
const fs = require('fs');
const path = require('path');

const locale = process.argv[2];
if (!locale) { console.error('Usage: node score.js <locale>'); process.exit(1); }

const LANG_NAMES = {
  'en-us': 'English', 'fr-fr': 'French', 'de-de': 'German', 'it-it': 'Italian',
  'es-es': 'Spanish', 'ja-jp': 'Japanese', 'zh-hk': 'Traditional Chinese (Hong Kong)',
  'zh-cn': 'Simplified Chinese', 'ko-kr': 'Korean', 'el-gr': 'Greek',
  'ru-ru': 'Russian', 'pt-pt': 'Portuguese', 'nl-nl': 'Dutch',
  'en-ca': 'English (Canada)', 'en-in': 'English (India)', 'en-gb': 'English (UK)',
  'en-za': 'English (South Africa)', 'en-au': 'English (Australia)',
  'en-sg': 'English (Singapore)', 'zh-tw': 'Traditional Chinese (Taiwan)',
  'en-nz': 'English (New Zealand)', 'th-th': 'Thai', 'ms-my': 'Malay',
  'vi-vn': 'Vietnamese', 'sv-se': 'Swedish', 'id-id': 'Indonesian',
  'pl-pl': 'Polish', 'nb-no': 'Norwegian', 'da-dk': 'Danish', 'fi-fi': 'Finnish',
  'cs-cz': 'Czech', 'tr-tr': 'Turkish', 'ca-es': 'Catalan', 'hu-hu': 'Hungarian',
  'hi-in': 'Hindi', 'bg-bg': 'Bulgarian', 'ro-ro': 'Romanian', 'sl-si': 'Slovenian',
  'he-il': 'Hebrew', 'ar-ae': 'Arabic', 'nl-be': 'Dutch (Belgium)',
  'en-ie': 'English (Ireland)', 'pt-br': 'Portuguese (Brazil)',
  'es-ar': 'Spanish (Argentina)', 'es-mx': 'Spanish (Mexico)',
  'lt-lt': 'Lithuanian', 'lv-lv': 'Latvian', 'hr-hr': 'Croatian',
  'et-ee': 'Estonian', 'uk-ua': 'Ukrainian', 'tl-ph': 'Filipino',
  'fr-ca': 'French (Canada)',
};
const langName = LANG_NAMES[locale] || locale;

const OUTPUT_DIR = process.env.OUTPUT_DIR;
if (!OUTPUT_DIR) { console.error('OUTPUT_DIR env var is required'); process.exit(1); }

const outputDir = path.resolve(OUTPUT_DIR);
const tag = process.env.RUN_TAG ? `-${process.env.RUN_TAG}` : '';
const INPUT_CSV = path.join(outputDir, `results${tag}-${locale}.csv`);
const OUTPUT_CSV = path.join(outputDir, `scored${tag}-${locale}.csv`);
const SCORE_MODEL = process.env.SCORE_MODEL || 'gemini-3.1-pro-preview';
const SCORE_CONCURRENCY = Math.max(1, parseInt(process.env.SCORE_CONCURRENCY, 10) || 5);

const client = new OpenAI({
  baseURL: process.env.OPENAI_BASE_URL || 'https://genai-gateway.agoda.is/v1',
});

const SCORING_PROMPT = `You are an expert content quality evaluator for a travel booking platform (Agoda).
You will be given the ORIGINAL (A-side) and ENHANCED (B-side) content for an activity listing in ${langName} language.
The enhanced content was generated by GPT to improve SEO and user experience.

You will receive:
- Title (A vs B)
- Description/overview (A vs B)
- Full list of page sections with content lengths and previews for BOTH sides

IMPORTANT: The B-side may reorganize content across sections differently than the A-side.
Information that appears in one section on A-side may appear in a different section on B-side.
Do NOT penalize B-side for having a concise summary in one section if the detailed information
exists elsewhere in another section. Evaluate completeness holistically across ALL sections.

Score each dimension 0-100 where 0=terrible, 50=no improvement, 100=perfect enhancement.

Dimensions:
- fluency: How natural and smooth the ${langName} text reads
- grammar: Correctness of ${langName} grammar, spelling, punctuation
- structure: User-friendly formatting, clear sections, readability
- relevance: Content stays true to the activity, no hallucination or irrelevant info
- completeness: Key activity details are preserved across ALL sections combined (not per-section)
- tone: Appropriate travel/marketing tone, engaging but not overselling

Return ONLY a JSON object with these exact keys (no markdown, no explanation):
{"fluency":N,"grammar":N,"structure":N,"relevance":N,"completeness":N,"tone":N}`;

function parseCSVRow(row) {
  const fields = []; let current = ''; let inQuotes = false;
  for (let i = 0; i < row.length; i++) {
    const ch = row[i];
    if (inQuotes) {
      if (ch === '"' && row[i + 1] === '"') { current += '"'; i++; }
      else if (ch === '"') { inQuotes = false; }
      else { current += ch; }
    } else {
      if (ch === '"') { inQuotes = true; }
      else if (ch === ',') { fields.push(current); current = ''; }
      else { current += ch; }
    }
  }
  fields.push(current);
  return fields;
}

function csvEscape(str) {
  if (!str) return '';
  str = String(str).replace(/\r?\n/g, ' ').replace(/\s+/g, ' ').trim();
  if (str.includes(',') || str.includes('"')) {
    return '"' + str.replace(/"/g, '""') + '"';
  }
  return str;
}

function formatSections(sectionsJson) {
  try {
    const sections = JSON.parse(sectionsJson);
    if (!Array.isArray(sections) || sections.length === 0) return '(no sections found)';
    return sections.map(s =>
      `  [${s.name}] (${s.content_length} chars): ${s.content_preview || ''}`
    ).join('\n');
  } catch {
    return '(no sections)';
  }
}

function sectionSummary(sectionsJson) {
  try {
    const sections = JSON.parse(sectionsJson);
    if (!Array.isArray(sections)) return '';
    return sections.map(s => s.name).join(' | ');
  } catch { return ''; }
}

async function scoreActivity(fields) {
  const [activityId, aTitle, bTitle, aDesc, bDesc, aSectionsJson, bSectionsJson, aError, bError] = fields;

  if (!bTitle && !bDesc && (!bSectionsJson || bSectionsJson === '[]')) {
    return { fluency: 0, grammar: 0, structure: 0, relevance: 0, completeness: 0, tone: 0, error: 'no_b_content' };
  }

  const aSections = formatSections(aSectionsJson);
  const bSections = formatSections(bSectionsJson);

  const userMessage = `Activity ID: ${activityId}

=== TITLE ===
ORIGINAL (A): ${aTitle || '(empty)'}
ENHANCED (B): ${bTitle || '(empty)'}

=== DESCRIPTION/OVERVIEW ===
ORIGINAL (A): ${(aDesc || '(empty)').substring(0, 1000)}
ENHANCED (B): ${(bDesc || '(empty)').substring(0, 1000)}

=== A-SIDE SECTIONS (all page sections) ===
${aSections}

=== B-SIDE SECTIONS (all page sections) ===
${bSections}`;

  for (let attempt = 0; ; attempt++) {
    try {
      const response = await client.chat.completions.create({
        model: SCORE_MODEL,
        messages: [
          { role: 'system', content: SCORING_PROMPT },
          { role: 'user', content: userMessage },
        ],
        temperature: 0.1, max_tokens: 2000,
      });

      const text = response.choices[0].message.content.trim();
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (!jsonMatch) throw new Error('No JSON in response');
      const scores = JSON.parse(jsonMatch[0]);
      for (const key of ['fluency', 'grammar', 'structure', 'relevance', 'completeness', 'tone']) {
        if (typeof scores[key] !== 'number' || scores[key] < 0 || scores[key] > 100) {
          scores[key] = Math.max(0, Math.min(100, Number(scores[key]) || 0));
        }
      }
      return { ...scores, error: '' };
    } catch (err) {
      const status = err.status || err.statusCode;
      const retryable = status === 429 || (status >= 500 && status < 600);
      if (retryable && attempt < 2) {
        const delay = 1000 * Math.pow(2, attempt);
        console.warn(`  [${locale}] Retry ${attempt + 1} for ${activityId} (${status}), waiting ${delay}ms`);
        await new Promise(r => setTimeout(r, delay));
        continue;
      }
      console.error(`  [${locale}] Score error ${activityId}: ${err.message.substring(0, 60)}`);
      return { fluency: 0, grammar: 0, structure: 0, relevance: 0, completeness: 0, tone: 0, error: err.message.substring(0, 80) };
    }
  }
}

const CSV_HEADER = 'activity_id,fluency,grammar,structure,relevance,completeness,tone,a_title,b_title,a_section_names,b_section_names,score_error';

function getScoredIds() {
  if (!fs.existsSync(OUTPUT_CSV)) return new Set();
  const lines = fs.readFileSync(OUTPUT_CSV, 'utf-8').split('\n').filter(l => l.trim());
  if (lines.length <= 1) return new Set();
  const ids = new Set();
  for (const line of lines.slice(1)) {
    const id = line.split(',')[0];
    if (id && /^\d+$/.test(id)) ids.add(id);
  }
  return ids;
}

let writeQueue = Promise.resolve();
function appendCSVRow(row) {
  writeQueue = writeQueue.then(() => fs.appendFileSync(OUTPUT_CSV, row + '\n'));
  return writeQueue;
}

(async () => {
  console.log(`[${locale}] Reading: ${INPUT_CSV}`);
  const lines = fs.readFileSync(INPUT_CSV, 'utf-8').split('\n').filter(l => l.trim());
  const dataRows = lines.slice(1);

  const scoredIds = getScoredIds();
  const remaining = dataRows.filter(line => {
    const id = parseCSVRow(line)[0];
    return !scoredIds.has(id);
  });
  const totalRows = dataRows.length;
  console.log(`[${locale}] Total: ${totalRows}, Already scored: ${scoredIds.size}, Remaining: ${remaining.length}, Concurrency: ${SCORE_CONCURRENCY}`);

  if (remaining.length === 0) { console.log(`[${locale}] All done!`); return; }

  if (!fs.existsSync(OUTPUT_CSV)) {
    fs.writeFileSync(OUTPUT_CSV, CSV_HEADER + '\n');
  }

  let scored = scoredIds.size;
  const dims = ['fluency', 'grammar', 'structure', 'relevance', 'completeness', 'tone'];
  const sums = dims.map(() => 0);
  let validCount = 0;

  async function processRow(line) {
    const fields = parseCSVRow(line);
    const bError = fields[8] || '';

    if (bError) {
      const row = [fields[0], 0, 0, 0, 0, 0, 0, csvEscape(fields[1]), csvEscape(fields[2]), '', '', csvEscape('extraction_error')].join(',');
      await appendCSVRow(row);
      scored++;
      return;
    }

    const scores = await scoreActivity(fields);
    const row = [
      fields[0], scores.fluency, scores.grammar, scores.structure,
      scores.relevance, scores.completeness, scores.tone,
      csvEscape(fields[1]), csvEscape(fields[2]),
      csvEscape(sectionSummary(fields[5])), csvEscape(sectionSummary(fields[6])),
      csvEscape(scores.error),
    ].join(',');
    await appendCSVRow(row);

    const hasScores = dims.some(d => scores[d] > 0);
    if (hasScores) {
      validCount++;
      dims.forEach((d, i) => { sums[i] += scores[d]; });
    }

    scored++;
    if (scored % 10 === 0) console.log(`[${locale}] ${scored}/${totalRows} scored...`);
  }

  // Parallel executor with bounded concurrency
  const queue = [...remaining];
  const workers = Array.from({ length: SCORE_CONCURRENCY }, async () => {
    while (queue.length > 0) {
      const line = queue.shift();
      if (line) await processRow(line);
    }
  });
  await Promise.all(workers);

  console.log(`\n[${locale}] === SCORING COMPLETE ===`);
  console.log(`[${locale}] Scored: ${validCount}/${totalRows}`);
  console.log(`[${locale}] Averages:`);
  dims.forEach((d, i) => {
    const avg = validCount > 0 ? (sums[i] / validCount).toFixed(1) : 0;
    console.log(`  ${d.padEnd(15)} ${avg}`);
  });
  console.log(`[${locale}] Output: ${OUTPUT_CSV}`);
})();
