# Usage, run: $ brew bundle --file ~/.config/Brewfile #

# Screen customisation
tap 'FelixKratz/formulae'
brew 'borders'
tap 'nikitabobko/tap'
cask 'aerospace'
cask 'betterdisplay'

# Keyboard Remapper
tap 'yqrashawn/goku'
brew 'yqrashawn/goku/goku'
cask 'karabiner-elements'
cask 'homerow'

# Library Management
brew 'asdf'

# CLI Essentials
brew 'fzf'
brew 'ripgrep'
brew 'jq'
brew 'poppler'
brew 'ddgr'
brew 'pandoc'
brew 'starship'
brew 'zoxide'
brew 'eza'
brew 'yazi'
brew 'tmux'
brew 'tpm'
brew 'lazygit'
brew 'imagemagick'
brew 'tree-sitter'
brew 'mole'

# shell
brew 'fish'

# Development
cask 'postman'
cask 'ghostty'
cask 'font-jetbrains-mono'

# AI
brew 'pi-coding-agent'

# Agoda essentials
cask 'orbstack'
brew 'metalbear-co/mirrord/mirrord'

# Productivity
cask 'logi-options+'
cask 'raycast'
cask 'shottr'
cask 'lookaway'
cask 'hiddenbar'
cask 'spotify'
cask 'raindropio'
cask 'zen'
tap 'zennotes/tap'
cask 'zennotes'

